services:
  db:
    image: mariadb:12.2.1
    command: --mysql-native-password=ON
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${FARMERS_MARKET_DB}
      MYSQL_ROOT_PASSWORD: ${FARMERS_MARKET_DB_PASSWORD}